/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoadCredentialsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoadCredentialsResponse{}

// LoadCredentialsResponse struct for LoadCredentialsResponse
type LoadCredentialsResponse struct {
	StorageCredentials []StorageCredential `json:"storage-credentials"`
}

type _LoadCredentialsResponse LoadCredentialsResponse

// NewLoadCredentialsResponse instantiates a new LoadCredentialsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoadCredentialsResponse(storageCredentials []StorageCredential) *LoadCredentialsResponse {
	this := LoadCredentialsResponse{}
	this.StorageCredentials = storageCredentials
	return &this
}

// NewLoadCredentialsResponseWithDefaults instantiates a new LoadCredentialsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoadCredentialsResponseWithDefaults() *LoadCredentialsResponse {
	this := LoadCredentialsResponse{}
	return &this
}

// GetStorageCredentials returns the StorageCredentials field value
func (o *LoadCredentialsResponse) GetStorageCredentials() []StorageCredential {
	if o == nil {
		var ret []StorageCredential
		return ret
	}

	return o.StorageCredentials
}

// GetStorageCredentialsOk returns a tuple with the StorageCredentials field value
// and a boolean to check if the value has been set.
func (o *LoadCredentialsResponse) GetStorageCredentialsOk() ([]StorageCredential, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageCredentials, true
}

// SetStorageCredentials sets field value
func (o *LoadCredentialsResponse) SetStorageCredentials(v []StorageCredential) {
	o.StorageCredentials = v
}

func (o LoadCredentialsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoadCredentialsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["storage-credentials"] = o.StorageCredentials
	return toSerialize, nil
}

func (o *LoadCredentialsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"storage-credentials",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoadCredentialsResponse := _LoadCredentialsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoadCredentialsResponse)

	if err != nil {
		return err
	}

	*o = LoadCredentialsResponse(varLoadCredentialsResponse)

	return err
}

type NullableLoadCredentialsResponse struct {
	value *LoadCredentialsResponse
	isSet bool
}

func (v NullableLoadCredentialsResponse) Get() *LoadCredentialsResponse {
	return v.value
}

func (v *NullableLoadCredentialsResponse) Set(val *LoadCredentialsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLoadCredentialsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLoadCredentialsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoadCredentialsResponse(val *LoadCredentialsResponse) *NullableLoadCredentialsResponse {
	return &NullableLoadCredentialsResponse{value: val, isSet: true}
}

func (v NullableLoadCredentialsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoadCredentialsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


