/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssertViewUUID type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssertViewUUID{}

// AssertViewUUID The view UUID must match the requirement's `uuid`
type AssertViewUUID struct {
	Type string `json:"type"`
	Uuid string `json:"uuid"`
}

type _AssertViewUUID AssertViewUUID

// NewAssertViewUUID instantiates a new AssertViewUUID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssertViewUUID(type_ string, uuid string) *AssertViewUUID {
	this := AssertViewUUID{}
	this.Type = type_
	this.Uuid = uuid
	return &this
}

// NewAssertViewUUIDWithDefaults instantiates a new AssertViewUUID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssertViewUUIDWithDefaults() *AssertViewUUID {
	this := AssertViewUUID{}
	return &this
}

// GetType returns the Type field value
func (o *AssertViewUUID) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AssertViewUUID) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AssertViewUUID) SetType(v string) {
	o.Type = v
}

// GetUuid returns the Uuid field value
func (o *AssertViewUUID) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *AssertViewUUID) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *AssertViewUUID) SetUuid(v string) {
	o.Uuid = v
}

func (o AssertViewUUID) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssertViewUUID) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *AssertViewUUID) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssertViewUUID := _AssertViewUUID{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssertViewUUID)

	if err != nil {
		return err
	}

	*o = AssertViewUUID(varAssertViewUUID)

	return err
}

type NullableAssertViewUUID struct {
	value *AssertViewUUID
	isSet bool
}

func (v NullableAssertViewUUID) Get() *AssertViewUUID {
	return v.value
}

func (v *NullableAssertViewUUID) Set(val *AssertViewUUID) {
	v.value = val
	v.isSet = true
}

func (v NullableAssertViewUUID) IsSet() bool {
	return v.isSet
}

func (v *NullableAssertViewUUID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssertViewUUID(val *AssertViewUUID) *NullableAssertViewUUID {
	return &NullableAssertViewUUID{value: val, isSet: true}
}

func (v NullableAssertViewUUID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssertViewUUID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


