/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveSnapshotRefUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveSnapshotRefUpdate{}

// RemoveSnapshotRefUpdate struct for RemoveSnapshotRefUpdate
type RemoveSnapshotRefUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	RefName string `json:"ref-name"`
}

type _RemoveSnapshotRefUpdate RemoveSnapshotRefUpdate

// NewRemoveSnapshotRefUpdate instantiates a new RemoveSnapshotRefUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveSnapshotRefUpdate(refName string) *RemoveSnapshotRefUpdate {
	this := RemoveSnapshotRefUpdate{}
	return &this
}

// NewRemoveSnapshotRefUpdateWithDefaults instantiates a new RemoveSnapshotRefUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveSnapshotRefUpdateWithDefaults() *RemoveSnapshotRefUpdate {
	this := RemoveSnapshotRefUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *RemoveSnapshotRefUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveSnapshotRefUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *RemoveSnapshotRefUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *RemoveSnapshotRefUpdate) SetAction(v string) {
	o.Action = &v
}

// GetRefName returns the RefName field value
func (o *RemoveSnapshotRefUpdate) GetRefName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefName
}

// GetRefNameOk returns a tuple with the RefName field value
// and a boolean to check if the value has been set.
func (o *RemoveSnapshotRefUpdate) GetRefNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefName, true
}

// SetRefName sets field value
func (o *RemoveSnapshotRefUpdate) SetRefName(v string) {
	o.RefName = v
}

func (o RemoveSnapshotRefUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveSnapshotRefUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["ref-name"] = o.RefName
	return toSerialize, nil
}

func (o *RemoveSnapshotRefUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ref-name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveSnapshotRefUpdate := _RemoveSnapshotRefUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveSnapshotRefUpdate)

	if err != nil {
		return err
	}

	*o = RemoveSnapshotRefUpdate(varRemoveSnapshotRefUpdate)

	return err
}

type NullableRemoveSnapshotRefUpdate struct {
	value *RemoveSnapshotRefUpdate
	isSet bool
}

func (v NullableRemoveSnapshotRefUpdate) Get() *RemoveSnapshotRefUpdate {
	return v.value
}

func (v *NullableRemoveSnapshotRefUpdate) Set(val *RemoveSnapshotRefUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveSnapshotRefUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveSnapshotRefUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveSnapshotRefUpdate(val *RemoveSnapshotRefUpdate) *NullableRemoveSnapshotRefUpdate {
	return &NullableRemoveSnapshotRefUpdate{value: val, isSet: true}
}

func (v NullableRemoveSnapshotRefUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveSnapshotRefUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


