/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpgradeFormatVersionUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpgradeFormatVersionUpdate{}

// UpgradeFormatVersionUpdate struct for UpgradeFormatVersionUpdate
type UpgradeFormatVersionUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	FormatVersion int32 `json:"format-version"`
}

type _UpgradeFormatVersionUpdate UpgradeFormatVersionUpdate

// NewUpgradeFormatVersionUpdate instantiates a new UpgradeFormatVersionUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpgradeFormatVersionUpdate(formatVersion int32) *UpgradeFormatVersionUpdate {
	this := UpgradeFormatVersionUpdate{}
	return &this
}

// NewUpgradeFormatVersionUpdateWithDefaults instantiates a new UpgradeFormatVersionUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpgradeFormatVersionUpdateWithDefaults() *UpgradeFormatVersionUpdate {
	this := UpgradeFormatVersionUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *UpgradeFormatVersionUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpgradeFormatVersionUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *UpgradeFormatVersionUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *UpgradeFormatVersionUpdate) SetAction(v string) {
	o.Action = &v
}

// GetFormatVersion returns the FormatVersion field value
func (o *UpgradeFormatVersionUpdate) GetFormatVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FormatVersion
}

// GetFormatVersionOk returns a tuple with the FormatVersion field value
// and a boolean to check if the value has been set.
func (o *UpgradeFormatVersionUpdate) GetFormatVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormatVersion, true
}

// SetFormatVersion sets field value
func (o *UpgradeFormatVersionUpdate) SetFormatVersion(v int32) {
	o.FormatVersion = v
}

func (o UpgradeFormatVersionUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpgradeFormatVersionUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["format-version"] = o.FormatVersion
	return toSerialize, nil
}

func (o *UpgradeFormatVersionUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"format-version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpgradeFormatVersionUpdate := _UpgradeFormatVersionUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpgradeFormatVersionUpdate)

	if err != nil {
		return err
	}

	*o = UpgradeFormatVersionUpdate(varUpgradeFormatVersionUpdate)

	return err
}

type NullableUpgradeFormatVersionUpdate struct {
	value *UpgradeFormatVersionUpdate
	isSet bool
}

func (v NullableUpgradeFormatVersionUpdate) Get() *UpgradeFormatVersionUpdate {
	return v.value
}

func (v *NullableUpgradeFormatVersionUpdate) Set(val *UpgradeFormatVersionUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableUpgradeFormatVersionUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableUpgradeFormatVersionUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpgradeFormatVersionUpdate(val *UpgradeFormatVersionUpdate) *NullableUpgradeFormatVersionUpdate {
	return &NullableUpgradeFormatVersionUpdate{value: val, isSet: true}
}

func (v NullableUpgradeFormatVersionUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpgradeFormatVersionUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


