/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetLocationUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetLocationUpdate{}

// SetLocationUpdate struct for SetLocationUpdate
type SetLocationUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	Location string `json:"location"`
}

type _SetLocationUpdate SetLocationUpdate

// NewSetLocationUpdate instantiates a new SetLocationUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetLocationUpdate(location string) *SetLocationUpdate {
	this := SetLocationUpdate{}
	return &this
}

// NewSetLocationUpdateWithDefaults instantiates a new SetLocationUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetLocationUpdateWithDefaults() *SetLocationUpdate {
	this := SetLocationUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *SetLocationUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetLocationUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *SetLocationUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *SetLocationUpdate) SetAction(v string) {
	o.Action = &v
}

// GetLocation returns the Location field value
func (o *SetLocationUpdate) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *SetLocationUpdate) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *SetLocationUpdate) SetLocation(v string) {
	o.Location = v
}

func (o SetLocationUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetLocationUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["location"] = o.Location
	return toSerialize, nil
}

func (o *SetLocationUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"location",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetLocationUpdate := _SetLocationUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetLocationUpdate)

	if err != nil {
		return err
	}

	*o = SetLocationUpdate(varSetLocationUpdate)

	return err
}

type NullableSetLocationUpdate struct {
	value *SetLocationUpdate
	isSet bool
}

func (v NullableSetLocationUpdate) Get() *SetLocationUpdate {
	return v.value
}

func (v *NullableSetLocationUpdate) Set(val *SetLocationUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSetLocationUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSetLocationUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetLocationUpdate(val *SetLocationUpdate) *NullableSetLocationUpdate {
	return &NullableSetLocationUpdate{value: val, isSet: true}
}

func (v NullableSetLocationUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetLocationUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


