/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemovePartitionStatisticsUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemovePartitionStatisticsUpdate{}

// RemovePartitionStatisticsUpdate struct for RemovePartitionStatisticsUpdate
type RemovePartitionStatisticsUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	SnapshotId int64 `json:"snapshot-id"`
}

type _RemovePartitionStatisticsUpdate RemovePartitionStatisticsUpdate

// NewRemovePartitionStatisticsUpdate instantiates a new RemovePartitionStatisticsUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemovePartitionStatisticsUpdate(snapshotId int64) *RemovePartitionStatisticsUpdate {
	this := RemovePartitionStatisticsUpdate{}
	return &this
}

// NewRemovePartitionStatisticsUpdateWithDefaults instantiates a new RemovePartitionStatisticsUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemovePartitionStatisticsUpdateWithDefaults() *RemovePartitionStatisticsUpdate {
	this := RemovePartitionStatisticsUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *RemovePartitionStatisticsUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemovePartitionStatisticsUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *RemovePartitionStatisticsUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *RemovePartitionStatisticsUpdate) SetAction(v string) {
	o.Action = &v
}

// GetSnapshotId returns the SnapshotId field value
func (o *RemovePartitionStatisticsUpdate) GetSnapshotId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SnapshotId
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value
// and a boolean to check if the value has been set.
func (o *RemovePartitionStatisticsUpdate) GetSnapshotIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SnapshotId, true
}

// SetSnapshotId sets field value
func (o *RemovePartitionStatisticsUpdate) SetSnapshotId(v int64) {
	o.SnapshotId = v
}

func (o RemovePartitionStatisticsUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemovePartitionStatisticsUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["snapshot-id"] = o.SnapshotId
	return toSerialize, nil
}

func (o *RemovePartitionStatisticsUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"snapshot-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemovePartitionStatisticsUpdate := _RemovePartitionStatisticsUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemovePartitionStatisticsUpdate)

	if err != nil {
		return err
	}

	*o = RemovePartitionStatisticsUpdate(varRemovePartitionStatisticsUpdate)

	return err
}

type NullableRemovePartitionStatisticsUpdate struct {
	value *RemovePartitionStatisticsUpdate
	isSet bool
}

func (v NullableRemovePartitionStatisticsUpdate) Get() *RemovePartitionStatisticsUpdate {
	return v.value
}

func (v *NullableRemovePartitionStatisticsUpdate) Set(val *RemovePartitionStatisticsUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableRemovePartitionStatisticsUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableRemovePartitionStatisticsUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemovePartitionStatisticsUpdate(val *RemovePartitionStatisticsUpdate) *NullableRemovePartitionStatisticsUpdate {
	return &NullableRemovePartitionStatisticsUpdate{value: val, isSet: true}
}

func (v NullableRemovePartitionStatisticsUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemovePartitionStatisticsUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


