/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransformTerm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransformTerm{}

// TransformTerm struct for TransformTerm
type TransformTerm struct {
	Type string `json:"type"`
	Transform string `json:"transform"`
	Term string `json:"term"`
}

type _TransformTerm TransformTerm

// NewTransformTerm instantiates a new TransformTerm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransformTerm(type_ string, transform string, term string) *TransformTerm {
	this := TransformTerm{}
	this.Type = type_
	this.Transform = transform
	this.Term = term
	return &this
}

// NewTransformTermWithDefaults instantiates a new TransformTerm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransformTermWithDefaults() *TransformTerm {
	this := TransformTerm{}
	return &this
}

// GetType returns the Type field value
func (o *TransformTerm) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TransformTerm) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TransformTerm) SetType(v string) {
	o.Type = v
}

// GetTransform returns the Transform field value
func (o *TransformTerm) GetTransform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Transform
}

// GetTransformOk returns a tuple with the Transform field value
// and a boolean to check if the value has been set.
func (o *TransformTerm) GetTransformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transform, true
}

// SetTransform sets field value
func (o *TransformTerm) SetTransform(v string) {
	o.Transform = v
}

// GetTerm returns the Term field value
func (o *TransformTerm) GetTerm() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Term
}

// GetTermOk returns a tuple with the Term field value
// and a boolean to check if the value has been set.
func (o *TransformTerm) GetTermOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Term, true
}

// SetTerm sets field value
func (o *TransformTerm) SetTerm(v string) {
	o.Term = v
}

func (o TransformTerm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransformTerm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["transform"] = o.Transform
	toSerialize["term"] = o.Term
	return toSerialize, nil
}

func (o *TransformTerm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"transform",
		"term",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransformTerm := _TransformTerm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransformTerm)

	if err != nil {
		return err
	}

	*o = TransformTerm(varTransformTerm)

	return err
}

type NullableTransformTerm struct {
	value *TransformTerm
	isSet bool
}

func (v NullableTransformTerm) Get() *TransformTerm {
	return v.value
}

func (v *NullableTransformTerm) Set(val *TransformTerm) {
	v.value = val
	v.isSet = true
}

func (v NullableTransformTerm) IsSet() bool {
	return v.isSet
}

func (v *NullableTransformTerm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransformTerm(val *TransformTerm) *NullableTransformTerm {
	return &NullableTransformTerm{value: val, isSet: true}
}

func (v NullableTransformTerm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransformTerm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


