/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrueExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrueExpression{}

// TrueExpression struct for TrueExpression
type TrueExpression struct {
	Type string `json:"type"`
}

type _TrueExpression TrueExpression

// NewTrueExpression instantiates a new TrueExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrueExpression(type_ string) *TrueExpression {
	this := TrueExpression{}
	this.Type = type_
	return &this
}

// NewTrueExpressionWithDefaults instantiates a new TrueExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrueExpressionWithDefaults() *TrueExpression {
	this := TrueExpression{}
	return &this
}

// GetType returns the Type field value
func (o *TrueExpression) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TrueExpression) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TrueExpression) SetType(v string) {
	o.Type = v
}

func (o TrueExpression) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrueExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TrueExpression) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrueExpression := _TrueExpression{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrueExpression)

	if err != nil {
		return err
	}

	*o = TrueExpression(varTrueExpression)

	return err
}

type NullableTrueExpression struct {
	value *TrueExpression
	isSet bool
}

func (v NullableTrueExpression) Get() *TrueExpression {
	return v.value
}

func (v *NullableTrueExpression) Set(val *TrueExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableTrueExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableTrueExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrueExpression(val *TrueExpression) *NullableTrueExpression {
	return &NullableTrueExpression{value: val, isSet: true}
}

func (v NullableTrueExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrueExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


