/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
)

// checks if the ValueMap type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValueMap{}

// ValueMap struct for ValueMap
type ValueMap struct {
	// List of integer column ids for each corresponding value
	Keys []int32 `json:"keys,omitempty"`
	// List of primitive type values, matched to 'keys' by index
	Values []PrimitiveTypeValue `json:"values,omitempty"`
}

// NewValueMap instantiates a new ValueMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValueMap() *ValueMap {
	this := ValueMap{}
	return &this
}

// NewValueMapWithDefaults instantiates a new ValueMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValueMapWithDefaults() *ValueMap {
	this := ValueMap{}
	return &this
}

// GetKeys returns the Keys field value if set, zero value otherwise.
func (o *ValueMap) GetKeys() []int32 {
	if o == nil || IsNil(o.Keys) {
		var ret []int32
		return ret
	}
	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValueMap) GetKeysOk() ([]int32, bool) {
	if o == nil || IsNil(o.Keys) {
		return nil, false
	}
	return o.Keys, true
}

// HasKeys returns a boolean if a field has been set.
func (o *ValueMap) HasKeys() bool {
	if o != nil && !IsNil(o.Keys) {
		return true
	}

	return false
}

// SetKeys gets a reference to the given []int32 and assigns it to the Keys field.
func (o *ValueMap) SetKeys(v []int32) {
	o.Keys = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *ValueMap) GetValues() []PrimitiveTypeValue {
	if o == nil || IsNil(o.Values) {
		var ret []PrimitiveTypeValue
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValueMap) GetValuesOk() ([]PrimitiveTypeValue, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *ValueMap) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []PrimitiveTypeValue and assigns it to the Values field.
func (o *ValueMap) SetValues(v []PrimitiveTypeValue) {
	o.Values = v
}

func (o ValueMap) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValueMap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Keys) {
		toSerialize["keys"] = o.Keys
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

type NullableValueMap struct {
	value *ValueMap
	isSet bool
}

func (v NullableValueMap) Get() *ValueMap {
	return v.value
}

func (v *NullableValueMap) Set(val *ValueMap) {
	v.value = val
	v.isSet = true
}

func (v NullableValueMap) IsSet() bool {
	return v.isSet
}

func (v *NullableValueMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValueMap(val *ValueMap) *NullableValueMap {
	return &NullableValueMap{value: val, isSet: true}
}

func (v NullableValueMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValueMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


