/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FalseExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FalseExpression{}

// FalseExpression struct for FalseExpression
type FalseExpression struct {
	Type string `json:"type"`
}

type _FalseExpression FalseExpression

// NewFalseExpression instantiates a new FalseExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFalseExpression(type_ string) *FalseExpression {
	this := FalseExpression{}
	this.Type = type_
	return &this
}

// NewFalseExpressionWithDefaults instantiates a new FalseExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFalseExpressionWithDefaults() *FalseExpression {
	this := FalseExpression{}
	return &this
}

// GetType returns the Type field value
func (o *FalseExpression) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FalseExpression) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FalseExpression) SetType(v string) {
	o.Type = v
}

func (o FalseExpression) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FalseExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *FalseExpression) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFalseExpression := _FalseExpression{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFalseExpression)

	if err != nil {
		return err
	}

	*o = FalseExpression(varFalseExpression)

	return err
}

type NullableFalseExpression struct {
	value *FalseExpression
	isSet bool
}

func (v NullableFalseExpression) Get() *FalseExpression {
	return v.value
}

func (v *NullableFalseExpression) Set(val *FalseExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableFalseExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableFalseExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFalseExpression(val *FalseExpression) *NullableFalseExpression {
	return &NullableFalseExpression{value: val, isSet: true}
}

func (v NullableFalseExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFalseExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


