/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommitTransactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommitTransactionRequest{}

// CommitTransactionRequest struct for CommitTransactionRequest
type CommitTransactionRequest struct {
	TableChanges []CommitTableRequest `json:"table-changes"`
}

type _CommitTransactionRequest CommitTransactionRequest

// NewCommitTransactionRequest instantiates a new CommitTransactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitTransactionRequest(tableChanges []CommitTableRequest) *CommitTransactionRequest {
	this := CommitTransactionRequest{}
	this.TableChanges = tableChanges
	return &this
}

// NewCommitTransactionRequestWithDefaults instantiates a new CommitTransactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitTransactionRequestWithDefaults() *CommitTransactionRequest {
	this := CommitTransactionRequest{}
	return &this
}

// GetTableChanges returns the TableChanges field value
func (o *CommitTransactionRequest) GetTableChanges() []CommitTableRequest {
	if o == nil {
		var ret []CommitTableRequest
		return ret
	}

	return o.TableChanges
}

// GetTableChangesOk returns a tuple with the TableChanges field value
// and a boolean to check if the value has been set.
func (o *CommitTransactionRequest) GetTableChangesOk() ([]CommitTableRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.TableChanges, true
}

// SetTableChanges sets field value
func (o *CommitTransactionRequest) SetTableChanges(v []CommitTableRequest) {
	o.TableChanges = v
}

func (o CommitTransactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommitTransactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["table-changes"] = o.TableChanges
	return toSerialize, nil
}

func (o *CommitTransactionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"table-changes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommitTransactionRequest := _CommitTransactionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommitTransactionRequest)

	if err != nil {
		return err
	}

	*o = CommitTransactionRequest(varCommitTransactionRequest)

	return err
}

type NullableCommitTransactionRequest struct {
	value *CommitTransactionRequest
	isSet bool
}

func (v NullableCommitTransactionRequest) Get() *CommitTransactionRequest {
	return v.value
}

func (v *NullableCommitTransactionRequest) Set(val *CommitTransactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitTransactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitTransactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitTransactionRequest(val *CommitTransactionRequest) *NullableCommitTransactionRequest {
	return &NullableCommitTransactionRequest{value: val, isSet: true}
}

func (v NullableCommitTransactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitTransactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


