/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetCurrentViewVersionUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetCurrentViewVersionUpdate{}

// SetCurrentViewVersionUpdate struct for SetCurrentViewVersionUpdate
type SetCurrentViewVersionUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	// The view version id to set as current, or -1 to set last added view version id
	ViewVersionId int32 `json:"view-version-id"`
}

type _SetCurrentViewVersionUpdate SetCurrentViewVersionUpdate

// NewSetCurrentViewVersionUpdate instantiates a new SetCurrentViewVersionUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetCurrentViewVersionUpdate(viewVersionId int32) *SetCurrentViewVersionUpdate {
	this := SetCurrentViewVersionUpdate{}
	return &this
}

// NewSetCurrentViewVersionUpdateWithDefaults instantiates a new SetCurrentViewVersionUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetCurrentViewVersionUpdateWithDefaults() *SetCurrentViewVersionUpdate {
	this := SetCurrentViewVersionUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *SetCurrentViewVersionUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetCurrentViewVersionUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *SetCurrentViewVersionUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *SetCurrentViewVersionUpdate) SetAction(v string) {
	o.Action = &v
}

// GetViewVersionId returns the ViewVersionId field value
func (o *SetCurrentViewVersionUpdate) GetViewVersionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ViewVersionId
}

// GetViewVersionIdOk returns a tuple with the ViewVersionId field value
// and a boolean to check if the value has been set.
func (o *SetCurrentViewVersionUpdate) GetViewVersionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ViewVersionId, true
}

// SetViewVersionId sets field value
func (o *SetCurrentViewVersionUpdate) SetViewVersionId(v int32) {
	o.ViewVersionId = v
}

func (o SetCurrentViewVersionUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetCurrentViewVersionUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["view-version-id"] = o.ViewVersionId
	return toSerialize, nil
}

func (o *SetCurrentViewVersionUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"view-version-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetCurrentViewVersionUpdate := _SetCurrentViewVersionUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetCurrentViewVersionUpdate)

	if err != nil {
		return err
	}

	*o = SetCurrentViewVersionUpdate(varSetCurrentViewVersionUpdate)

	return err
}

type NullableSetCurrentViewVersionUpdate struct {
	value *SetCurrentViewVersionUpdate
	isSet bool
}

func (v NullableSetCurrentViewVersionUpdate) Get() *SetCurrentViewVersionUpdate {
	return v.value
}

func (v *NullableSetCurrentViewVersionUpdate) Set(val *SetCurrentViewVersionUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSetCurrentViewVersionUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSetCurrentViewVersionUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetCurrentViewVersionUpdate(val *SetCurrentViewVersionUpdate) *NullableSetCurrentViewVersionUpdate {
	return &NullableSetCurrentViewVersionUpdate{value: val, isSet: true}
}

func (v NullableSetCurrentViewVersionUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetCurrentViewVersionUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


