/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssertTableUUID type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssertTableUUID{}

// AssertTableUUID The table UUID must match the requirement's `uuid`
type AssertTableUUID struct {
	TableRequirement
	Type string `json:"type"`
	Uuid string `json:"uuid"`
}

type _AssertTableUUID AssertTableUUID

// NewAssertTableUUID instantiates a new AssertTableUUID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssertTableUUID(type_ string, uuid string) *AssertTableUUID {
	this := AssertTableUUID{}
	this.Type = type_
	return &this
}

// NewAssertTableUUIDWithDefaults instantiates a new AssertTableUUID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssertTableUUIDWithDefaults() *AssertTableUUID {
	this := AssertTableUUID{}
	return &this
}

// GetType returns the Type field value
func (o *AssertTableUUID) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AssertTableUUID) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AssertTableUUID) SetType(v string) {
	o.Type = v
}

// GetUuid returns the Uuid field value
func (o *AssertTableUUID) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *AssertTableUUID) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *AssertTableUUID) SetUuid(v string) {
	o.Uuid = v
}

func (o AssertTableUUID) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssertTableUUID) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedTableRequirement, errTableRequirement := json.Marshal(o.TableRequirement)
	if errTableRequirement != nil {
		return map[string]interface{}{}, errTableRequirement
	}
	errTableRequirement = json.Unmarshal([]byte(serializedTableRequirement), &toSerialize)
	if errTableRequirement != nil {
		return map[string]interface{}{}, errTableRequirement
	}
	toSerialize["type"] = o.Type
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

func (o *AssertTableUUID) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssertTableUUID := _AssertTableUUID{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssertTableUUID)

	if err != nil {
		return err
	}

	*o = AssertTableUUID(varAssertTableUUID)

	return err
}

type NullableAssertTableUUID struct {
	value *AssertTableUUID
	isSet bool
}

func (v NullableAssertTableUUID) Get() *AssertTableUUID {
	return v.value
}

func (v *NullableAssertTableUUID) Set(val *AssertTableUUID) {
	v.value = val
	v.isSet = true
}

func (v NullableAssertTableUUID) IsSet() bool {
	return v.isSet
}

func (v *NullableAssertTableUUID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssertTableUUID(val *AssertTableUUID) *NullableAssertTableUUID {
	return &NullableAssertTableUUID{value: val, isSet: true}
}

func (v NullableAssertTableUUID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssertTableUUID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


