/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveSchemasUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveSchemasUpdate{}

// RemoveSchemasUpdate struct for RemoveSchemasUpdate
type RemoveSchemasUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	SchemaIds []int32 `json:"schema-ids"`
}

type _RemoveSchemasUpdate RemoveSchemasUpdate

// NewRemoveSchemasUpdate instantiates a new RemoveSchemasUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveSchemasUpdate(schemaIds []int32) *RemoveSchemasUpdate {
	this := RemoveSchemasUpdate{}
	return &this
}

// NewRemoveSchemasUpdateWithDefaults instantiates a new RemoveSchemasUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveSchemasUpdateWithDefaults() *RemoveSchemasUpdate {
	this := RemoveSchemasUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *RemoveSchemasUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveSchemasUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *RemoveSchemasUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *RemoveSchemasUpdate) SetAction(v string) {
	o.Action = &v
}

// GetSchemaIds returns the SchemaIds field value
func (o *RemoveSchemasUpdate) GetSchemaIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.SchemaIds
}

// GetSchemaIdsOk returns a tuple with the SchemaIds field value
// and a boolean to check if the value has been set.
func (o *RemoveSchemasUpdate) GetSchemaIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SchemaIds, true
}

// SetSchemaIds sets field value
func (o *RemoveSchemasUpdate) SetSchemaIds(v []int32) {
	o.SchemaIds = v
}

func (o RemoveSchemasUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveSchemasUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["schema-ids"] = o.SchemaIds
	return toSerialize, nil
}

func (o *RemoveSchemasUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schema-ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveSchemasUpdate := _RemoveSchemasUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveSchemasUpdate)

	if err != nil {
		return err
	}

	*o = RemoveSchemasUpdate(varRemoveSchemasUpdate)

	return err
}

type NullableRemoveSchemasUpdate struct {
	value *RemoveSchemasUpdate
	isSet bool
}

func (v NullableRemoveSchemasUpdate) Get() *RemoveSchemasUpdate {
	return v.value
}

func (v *NullableRemoveSchemasUpdate) Set(val *RemoveSchemasUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveSchemasUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveSchemasUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveSchemasUpdate(val *RemoveSchemasUpdate) *NullableRemoveSchemasUpdate {
	return &NullableRemoveSchemasUpdate{value: val, isSet: true}
}

func (v NullableRemoveSchemasUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveSchemasUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


