/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TableRequirement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableRequirement{}

// TableRequirement struct for TableRequirement
type TableRequirement struct {
	Type string `json:"type"`
}

type _TableRequirement TableRequirement

// NewTableRequirement instantiates a new TableRequirement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableRequirement(type_ string) *TableRequirement {
	this := TableRequirement{}
	this.Type = type_
	return &this
}

// NewTableRequirementWithDefaults instantiates a new TableRequirement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableRequirementWithDefaults() *TableRequirement {
	this := TableRequirement{}
	return &this
}

// GetType returns the Type field value
func (o *TableRequirement) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TableRequirement) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TableRequirement) SetType(v string) {
	o.Type = v
}

func (o TableRequirement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableRequirement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *TableRequirement) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableRequirement := _TableRequirement{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTableRequirement)

	if err != nil {
		return err
	}

	*o = TableRequirement(varTableRequirement)

	return err
}

type NullableTableRequirement struct {
	value *TableRequirement
	isSet bool
}

func (v NullableTableRequirement) Get() *TableRequirement {
	return v.value
}

func (v *NullableTableRequirement) Set(val *TableRequirement) {
	v.value = val
	v.isSet = true
}

func (v NullableTableRequirement) IsSet() bool {
	return v.isSet
}

func (v *NullableTableRequirement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableRequirement(val *TableRequirement) *NullableTableRequirement {
	return &NullableTableRequirement{value: val, isSet: true}
}

func (v NullableTableRequirement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableRequirement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


