/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemovePropertiesUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemovePropertiesUpdate{}

// RemovePropertiesUpdate struct for RemovePropertiesUpdate
type RemovePropertiesUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	Removals []string `json:"removals"`
}

type _RemovePropertiesUpdate RemovePropertiesUpdate

// NewRemovePropertiesUpdate instantiates a new RemovePropertiesUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemovePropertiesUpdate(removals []string) *RemovePropertiesUpdate {
	this := RemovePropertiesUpdate{}
	return &this
}

// NewRemovePropertiesUpdateWithDefaults instantiates a new RemovePropertiesUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemovePropertiesUpdateWithDefaults() *RemovePropertiesUpdate {
	this := RemovePropertiesUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *RemovePropertiesUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemovePropertiesUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *RemovePropertiesUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *RemovePropertiesUpdate) SetAction(v string) {
	o.Action = &v
}

// GetRemovals returns the Removals field value
func (o *RemovePropertiesUpdate) GetRemovals() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Removals
}

// GetRemovalsOk returns a tuple with the Removals field value
// and a boolean to check if the value has been set.
func (o *RemovePropertiesUpdate) GetRemovalsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Removals, true
}

// SetRemovals sets field value
func (o *RemovePropertiesUpdate) SetRemovals(v []string) {
	o.Removals = v
}

func (o RemovePropertiesUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemovePropertiesUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["removals"] = o.Removals
	return toSerialize, nil
}

func (o *RemovePropertiesUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"removals",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemovePropertiesUpdate := _RemovePropertiesUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemovePropertiesUpdate)

	if err != nil {
		return err
	}

	*o = RemovePropertiesUpdate(varRemovePropertiesUpdate)

	return err
}

type NullableRemovePropertiesUpdate struct {
	value *RemovePropertiesUpdate
	isSet bool
}

func (v NullableRemovePropertiesUpdate) Get() *RemovePropertiesUpdate {
	return v.value
}

func (v *NullableRemovePropertiesUpdate) Set(val *RemovePropertiesUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableRemovePropertiesUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableRemovePropertiesUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemovePropertiesUpdate(val *RemovePropertiesUpdate) *NullableRemovePropertiesUpdate {
	return &NullableRemovePropertiesUpdate{value: val, isSet: true}
}

func (v NullableRemovePropertiesUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemovePropertiesUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


