/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddSortOrderUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddSortOrderUpdate{}

// AddSortOrderUpdate struct for AddSortOrderUpdate
type AddSortOrderUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	SortOrder SortOrder `json:"sort-order"`
}

type _AddSortOrderUpdate AddSortOrderUpdate

// NewAddSortOrderUpdate instantiates a new AddSortOrderUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddSortOrderUpdate(sortOrder SortOrder) *AddSortOrderUpdate {
	this := AddSortOrderUpdate{}
	return &this
}

// NewAddSortOrderUpdateWithDefaults instantiates a new AddSortOrderUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddSortOrderUpdateWithDefaults() *AddSortOrderUpdate {
	this := AddSortOrderUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *AddSortOrderUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddSortOrderUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *AddSortOrderUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *AddSortOrderUpdate) SetAction(v string) {
	o.Action = &v
}

// GetSortOrder returns the SortOrder field value
func (o *AddSortOrderUpdate) GetSortOrder() SortOrder {
	if o == nil {
		var ret SortOrder
		return ret
	}

	return o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value
// and a boolean to check if the value has been set.
func (o *AddSortOrderUpdate) GetSortOrderOk() (*SortOrder, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SortOrder, true
}

// SetSortOrder sets field value
func (o *AddSortOrderUpdate) SetSortOrder(v SortOrder) {
	o.SortOrder = v
}

func (o AddSortOrderUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddSortOrderUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["sort-order"] = o.SortOrder
	return toSerialize, nil
}

func (o *AddSortOrderUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sort-order",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddSortOrderUpdate := _AddSortOrderUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddSortOrderUpdate)

	if err != nil {
		return err
	}

	*o = AddSortOrderUpdate(varAddSortOrderUpdate)

	return err
}

type NullableAddSortOrderUpdate struct {
	value *AddSortOrderUpdate
	isSet bool
}

func (v NullableAddSortOrderUpdate) Get() *AddSortOrderUpdate {
	return v.value
}

func (v *NullableAddSortOrderUpdate) Set(val *AddSortOrderUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableAddSortOrderUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableAddSortOrderUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddSortOrderUpdate(val *AddSortOrderUpdate) *NullableAddSortOrderUpdate {
	return &NullableAddSortOrderUpdate{value: val, isSet: true}
}

func (v NullableAddSortOrderUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddSortOrderUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


