/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// Term - struct for Term
type Term struct {
	TransformTerm *TransformTerm
	String *string
}

// TransformTermAsTerm is a convenience function that returns TransformTerm wrapped in Term
func TransformTermAsTerm(v *TransformTerm) Term {
	return Term{
		TransformTerm: v,
	}
}

// stringAsTerm is a convenience function that returns string wrapped in Term
func StringAsTerm(v *string) Term {
	return Term{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Term) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TransformTerm
	err = newStrictDecoder(data).Decode(&dst.TransformTerm)
	if err == nil {
		jsonTransformTerm, _ := json.Marshal(dst.TransformTerm)
		if string(jsonTransformTerm) == "{}" { // empty struct
			dst.TransformTerm = nil
		} else {
			if err = validator.Validate(dst.TransformTerm); err != nil {
				dst.TransformTerm = nil
			} else {
				match++
			}
		}
	} else {
		dst.TransformTerm = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TransformTerm = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Term)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Term)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Term) MarshalJSON() ([]byte, error) {
	if src.TransformTerm != nil {
		return json.Marshal(&src.TransformTerm)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Term) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.TransformTerm != nil {
		return obj.TransformTerm
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Term) GetActualInstanceValue() (interface{}) {
	if obj.TransformTerm != nil {
		return *obj.TransformTerm
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableTerm struct {
	value *Term
	isSet bool
}

func (v NullableTerm) Get() *Term {
	return v.value
}

func (v *NullableTerm) Set(val *Term) {
	v.value = val
	v.isSet = true
}

func (v NullableTerm) IsSet() bool {
	return v.isSet
}

func (v *NullableTerm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerm(val *Term) *NullableTerm {
	return &NullableTerm{value: val, isSet: true}
}

func (v NullableTerm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


