/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
)

// checks if the ListTablesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTablesResponse{}

// ListTablesResponse struct for ListTablesResponse
type ListTablesResponse struct {
	// An opaque token that allows clients to make use of pagination for list APIs (e.g. ListTables). Clients may initiate the first paginated request by sending an empty query parameter `pageToken` to the server. Servers that support pagination should identify the `pageToken` parameter and return a `next-page-token` in the response if there are more results available.  After the initial request, the value of `next-page-token` from each response must be used as the `pageToken` parameter value for the next request. The server must return `null` value for the `next-page-token` in the last response. Servers that support pagination must return all results in a single response with the value of `next-page-token` set to `null` if the query parameter `pageToken` is not set in the request. Servers that do not support pagination should ignore the `pageToken` parameter and return all results in a single response. The `next-page-token` must be omitted from the response. Clients must interpret either `null` or missing response value of `next-page-token` as the end of the listing results.
	NextPageToken *string `json:"next-page-token,omitempty"`
	Identifiers []TableIdentifier `json:"identifiers,omitempty"`
}

// NewListTablesResponse instantiates a new ListTablesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTablesResponse() *ListTablesResponse {
	this := ListTablesResponse{}
	return &this
}

// NewListTablesResponseWithDefaults instantiates a new ListTablesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTablesResponseWithDefaults() *ListTablesResponse {
	this := ListTablesResponse{}
	return &this
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListTablesResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTablesResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListTablesResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListTablesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetIdentifiers returns the Identifiers field value if set, zero value otherwise.
func (o *ListTablesResponse) GetIdentifiers() []TableIdentifier {
	if o == nil || IsNil(o.Identifiers) {
		var ret []TableIdentifier
		return ret
	}
	return o.Identifiers
}

// GetIdentifiersOk returns a tuple with the Identifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTablesResponse) GetIdentifiersOk() ([]TableIdentifier, bool) {
	if o == nil || IsNil(o.Identifiers) {
		return nil, false
	}
	return o.Identifiers, true
}

// HasIdentifiers returns a boolean if a field has been set.
func (o *ListTablesResponse) HasIdentifiers() bool {
	if o != nil && !IsNil(o.Identifiers) {
		return true
	}

	return false
}

// SetIdentifiers gets a reference to the given []TableIdentifier and assigns it to the Identifiers field.
func (o *ListTablesResponse) SetIdentifiers(v []TableIdentifier) {
	o.Identifiers = v
}

func (o ListTablesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTablesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextPageToken) {
		toSerialize["next-page-token"] = o.NextPageToken
	}
	if !IsNil(o.Identifiers) {
		toSerialize["identifiers"] = o.Identifiers
	}
	return toSerialize, nil
}

type NullableListTablesResponse struct {
	value *ListTablesResponse
	isSet bool
}

func (v NullableListTablesResponse) Get() *ListTablesResponse {
	return v.value
}

func (v *NullableListTablesResponse) Set(val *ListTablesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListTablesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListTablesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTablesResponse(val *ListTablesResponse) *NullableListTablesResponse {
	return &NullableListTablesResponse{value: val, isSet: true}
}

func (v NullableListTablesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTablesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


