/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemovePartitionSpecsUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemovePartitionSpecsUpdate{}

// RemovePartitionSpecsUpdate struct for RemovePartitionSpecsUpdate
type RemovePartitionSpecsUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	SpecIds []int32 `json:"spec-ids"`
}

type _RemovePartitionSpecsUpdate RemovePartitionSpecsUpdate

// NewRemovePartitionSpecsUpdate instantiates a new RemovePartitionSpecsUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemovePartitionSpecsUpdate(specIds []int32) *RemovePartitionSpecsUpdate {
	this := RemovePartitionSpecsUpdate{}
	return &this
}

// NewRemovePartitionSpecsUpdateWithDefaults instantiates a new RemovePartitionSpecsUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemovePartitionSpecsUpdateWithDefaults() *RemovePartitionSpecsUpdate {
	this := RemovePartitionSpecsUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *RemovePartitionSpecsUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemovePartitionSpecsUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *RemovePartitionSpecsUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *RemovePartitionSpecsUpdate) SetAction(v string) {
	o.Action = &v
}

// GetSpecIds returns the SpecIds field value
func (o *RemovePartitionSpecsUpdate) GetSpecIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.SpecIds
}

// GetSpecIdsOk returns a tuple with the SpecIds field value
// and a boolean to check if the value has been set.
func (o *RemovePartitionSpecsUpdate) GetSpecIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpecIds, true
}

// SetSpecIds sets field value
func (o *RemovePartitionSpecsUpdate) SetSpecIds(v []int32) {
	o.SpecIds = v
}

func (o RemovePartitionSpecsUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemovePartitionSpecsUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["spec-ids"] = o.SpecIds
	return toSerialize, nil
}

func (o *RemovePartitionSpecsUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spec-ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemovePartitionSpecsUpdate := _RemovePartitionSpecsUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemovePartitionSpecsUpdate)

	if err != nil {
		return err
	}

	*o = RemovePartitionSpecsUpdate(varRemovePartitionSpecsUpdate)

	return err
}

type NullableRemovePartitionSpecsUpdate struct {
	value *RemovePartitionSpecsUpdate
	isSet bool
}

func (v NullableRemovePartitionSpecsUpdate) Get() *RemovePartitionSpecsUpdate {
	return v.value
}

func (v *NullableRemovePartitionSpecsUpdate) Set(val *RemovePartitionSpecsUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableRemovePartitionSpecsUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableRemovePartitionSpecsUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemovePartitionSpecsUpdate(val *RemovePartitionSpecsUpdate) *NullableRemovePartitionSpecsUpdate {
	return &NullableRemovePartitionSpecsUpdate{value: val, isSet: true}
}

func (v NullableRemovePartitionSpecsUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemovePartitionSpecsUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


