/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssertLastAssignedPartitionId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssertLastAssignedPartitionId{}

// AssertLastAssignedPartitionId The table's last assigned partition id must match the requirement's `last-assigned-partition-id`
type AssertLastAssignedPartitionId struct {
	TableRequirement
	Type *string `json:"type,omitempty"`
	LastAssignedPartitionId int32 `json:"last-assigned-partition-id"`
}

type _AssertLastAssignedPartitionId AssertLastAssignedPartitionId

// NewAssertLastAssignedPartitionId instantiates a new AssertLastAssignedPartitionId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssertLastAssignedPartitionId(lastAssignedPartitionId int32) *AssertLastAssignedPartitionId {
	this := AssertLastAssignedPartitionId{}
	return &this
}

// NewAssertLastAssignedPartitionIdWithDefaults instantiates a new AssertLastAssignedPartitionId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssertLastAssignedPartitionIdWithDefaults() *AssertLastAssignedPartitionId {
	this := AssertLastAssignedPartitionId{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AssertLastAssignedPartitionId) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertLastAssignedPartitionId) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AssertLastAssignedPartitionId) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AssertLastAssignedPartitionId) SetType(v string) {
	o.Type = &v
}

// GetLastAssignedPartitionId returns the LastAssignedPartitionId field value
func (o *AssertLastAssignedPartitionId) GetLastAssignedPartitionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LastAssignedPartitionId
}

// GetLastAssignedPartitionIdOk returns a tuple with the LastAssignedPartitionId field value
// and a boolean to check if the value has been set.
func (o *AssertLastAssignedPartitionId) GetLastAssignedPartitionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastAssignedPartitionId, true
}

// SetLastAssignedPartitionId sets field value
func (o *AssertLastAssignedPartitionId) SetLastAssignedPartitionId(v int32) {
	o.LastAssignedPartitionId = v
}

func (o AssertLastAssignedPartitionId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssertLastAssignedPartitionId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedTableRequirement, errTableRequirement := json.Marshal(o.TableRequirement)
	if errTableRequirement != nil {
		return map[string]interface{}{}, errTableRequirement
	}
	errTableRequirement = json.Unmarshal([]byte(serializedTableRequirement), &toSerialize)
	if errTableRequirement != nil {
		return map[string]interface{}{}, errTableRequirement
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["last-assigned-partition-id"] = o.LastAssignedPartitionId
	return toSerialize, nil
}

func (o *AssertLastAssignedPartitionId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"last-assigned-partition-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssertLastAssignedPartitionId := _AssertLastAssignedPartitionId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssertLastAssignedPartitionId)

	if err != nil {
		return err
	}

	*o = AssertLastAssignedPartitionId(varAssertLastAssignedPartitionId)

	return err
}

type NullableAssertLastAssignedPartitionId struct {
	value *AssertLastAssignedPartitionId
	isSet bool
}

func (v NullableAssertLastAssignedPartitionId) Get() *AssertLastAssignedPartitionId {
	return v.value
}

func (v *NullableAssertLastAssignedPartitionId) Set(val *AssertLastAssignedPartitionId) {
	v.value = val
	v.isSet = true
}

func (v NullableAssertLastAssignedPartitionId) IsSet() bool {
	return v.isSet
}

func (v *NullableAssertLastAssignedPartitionId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssertLastAssignedPartitionId(val *AssertLastAssignedPartitionId) *NullableAssertLastAssignedPartitionId {
	return &NullableAssertLastAssignedPartitionId{value: val, isSet: true}
}

func (v NullableAssertLastAssignedPartitionId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssertLastAssignedPartitionId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


