/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NotExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotExpression{}

// NotExpression struct for NotExpression
type NotExpression struct {
	Type string `json:"type"`
	Child Expression `json:"child"`
}

type _NotExpression NotExpression

// NewNotExpression instantiates a new NotExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotExpression(type_ string, child Expression) *NotExpression {
	this := NotExpression{}
	this.Type = type_
	this.Child = child
	return &this
}

// NewNotExpressionWithDefaults instantiates a new NotExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotExpressionWithDefaults() *NotExpression {
	this := NotExpression{}
	return &this
}

// GetType returns the Type field value
func (o *NotExpression) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NotExpression) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NotExpression) SetType(v string) {
	o.Type = v
}

// GetChild returns the Child field value
func (o *NotExpression) GetChild() Expression {
	if o == nil {
		var ret Expression
		return ret
	}

	return o.Child
}

// GetChildOk returns a tuple with the Child field value
// and a boolean to check if the value has been set.
func (o *NotExpression) GetChildOk() (*Expression, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Child, true
}

// SetChild sets field value
func (o *NotExpression) SetChild(v Expression) {
	o.Child = v
}

func (o NotExpression) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["child"] = o.Child
	return toSerialize, nil
}

func (o *NotExpression) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"child",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNotExpression := _NotExpression{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNotExpression)

	if err != nil {
		return err
	}

	*o = NotExpression(varNotExpression)

	return err
}

type NullableNotExpression struct {
	value *NotExpression
	isSet bool
}

func (v NullableNotExpression) Get() *NotExpression {
	return v.value
}

func (v *NullableNotExpression) Set(val *NotExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableNotExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableNotExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotExpression(val *NotExpression) *NullableNotExpression {
	return &NullableNotExpression{value: val, isSet: true}
}

func (v NullableNotExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


