/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssertDefaultSpecId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssertDefaultSpecId{}

// AssertDefaultSpecId The table's default spec id must match the requirement's `default-spec-id`
type AssertDefaultSpecId struct {
	TableRequirement
	Type *string `json:"type,omitempty"`
	DefaultSpecId int32 `json:"default-spec-id"`
}

type _AssertDefaultSpecId AssertDefaultSpecId

// NewAssertDefaultSpecId instantiates a new AssertDefaultSpecId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssertDefaultSpecId(defaultSpecId int32) *AssertDefaultSpecId {
	this := AssertDefaultSpecId{}
	return &this
}

// NewAssertDefaultSpecIdWithDefaults instantiates a new AssertDefaultSpecId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssertDefaultSpecIdWithDefaults() *AssertDefaultSpecId {
	this := AssertDefaultSpecId{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AssertDefaultSpecId) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssertDefaultSpecId) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AssertDefaultSpecId) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AssertDefaultSpecId) SetType(v string) {
	o.Type = &v
}

// GetDefaultSpecId returns the DefaultSpecId field value
func (o *AssertDefaultSpecId) GetDefaultSpecId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DefaultSpecId
}

// GetDefaultSpecIdOk returns a tuple with the DefaultSpecId field value
// and a boolean to check if the value has been set.
func (o *AssertDefaultSpecId) GetDefaultSpecIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultSpecId, true
}

// SetDefaultSpecId sets field value
func (o *AssertDefaultSpecId) SetDefaultSpecId(v int32) {
	o.DefaultSpecId = v
}

func (o AssertDefaultSpecId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssertDefaultSpecId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedTableRequirement, errTableRequirement := json.Marshal(o.TableRequirement)
	if errTableRequirement != nil {
		return map[string]interface{}{}, errTableRequirement
	}
	errTableRequirement = json.Unmarshal([]byte(serializedTableRequirement), &toSerialize)
	if errTableRequirement != nil {
		return map[string]interface{}{}, errTableRequirement
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["default-spec-id"] = o.DefaultSpecId
	return toSerialize, nil
}

func (o *AssertDefaultSpecId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"default-spec-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssertDefaultSpecId := _AssertDefaultSpecId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssertDefaultSpecId)

	if err != nil {
		return err
	}

	*o = AssertDefaultSpecId(varAssertDefaultSpecId)

	return err
}

type NullableAssertDefaultSpecId struct {
	value *AssertDefaultSpecId
	isSet bool
}

func (v NullableAssertDefaultSpecId) Get() *AssertDefaultSpecId {
	return v.value
}

func (v *NullableAssertDefaultSpecId) Set(val *AssertDefaultSpecId) {
	v.value = val
	v.isSet = true
}

func (v NullableAssertDefaultSpecId) IsSet() bool {
	return v.isSet
}

func (v *NullableAssertDefaultSpecId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssertDefaultSpecId(val *AssertDefaultSpecId) *NullableAssertDefaultSpecId {
	return &NullableAssertDefaultSpecId{value: val, isSet: true}
}

func (v NullableAssertDefaultSpecId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssertDefaultSpecId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


