/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddPartitionSpecUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddPartitionSpecUpdate{}

// AddPartitionSpecUpdate struct for AddPartitionSpecUpdate
type AddPartitionSpecUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	Spec PartitionSpec `json:"spec"`
}

type _AddPartitionSpecUpdate AddPartitionSpecUpdate

// NewAddPartitionSpecUpdate instantiates a new AddPartitionSpecUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddPartitionSpecUpdate(spec PartitionSpec) *AddPartitionSpecUpdate {
	this := AddPartitionSpecUpdate{}
	return &this
}

// NewAddPartitionSpecUpdateWithDefaults instantiates a new AddPartitionSpecUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddPartitionSpecUpdateWithDefaults() *AddPartitionSpecUpdate {
	this := AddPartitionSpecUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *AddPartitionSpecUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddPartitionSpecUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *AddPartitionSpecUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *AddPartitionSpecUpdate) SetAction(v string) {
	o.Action = &v
}

// GetSpec returns the Spec field value
func (o *AddPartitionSpecUpdate) GetSpec() PartitionSpec {
	if o == nil {
		var ret PartitionSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *AddPartitionSpecUpdate) GetSpecOk() (*PartitionSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *AddPartitionSpecUpdate) SetSpec(v PartitionSpec) {
	o.Spec = v
}

func (o AddPartitionSpecUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddPartitionSpecUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["spec"] = o.Spec
	return toSerialize, nil
}

func (o *AddPartitionSpecUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spec",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddPartitionSpecUpdate := _AddPartitionSpecUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddPartitionSpecUpdate)

	if err != nil {
		return err
	}

	*o = AddPartitionSpecUpdate(varAddPartitionSpecUpdate)

	return err
}

type NullableAddPartitionSpecUpdate struct {
	value *AddPartitionSpecUpdate
	isSet bool
}

func (v NullableAddPartitionSpecUpdate) Get() *AddPartitionSpecUpdate {
	return v.value
}

func (v *NullableAddPartitionSpecUpdate) Set(val *AddPartitionSpecUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableAddPartitionSpecUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableAddPartitionSpecUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddPartitionSpecUpdate(val *AddPartitionSpecUpdate) *NullableAddPartitionSpecUpdate {
	return &NullableAddPartitionSpecUpdate{value: val, isSet: true}
}

func (v NullableAddPartitionSpecUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddPartitionSpecUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


