/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateNamespaceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNamespaceResponse{}

// CreateNamespaceResponse struct for CreateNamespaceResponse
type CreateNamespaceResponse struct {
	// Reference to one or more levels of a namespace
	Namespace []string `json:"namespace"`
	// Properties stored on the namespace, if supported by the server.
	Properties map[string]string `json:"properties,omitempty"`
}

type _CreateNamespaceResponse CreateNamespaceResponse

// NewCreateNamespaceResponse instantiates a new CreateNamespaceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNamespaceResponse(namespace []string) *CreateNamespaceResponse {
	this := CreateNamespaceResponse{}
	this.Namespace = namespace
	return &this
}

// NewCreateNamespaceResponseWithDefaults instantiates a new CreateNamespaceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNamespaceResponseWithDefaults() *CreateNamespaceResponse {
	this := CreateNamespaceResponse{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *CreateNamespaceResponse) GetNamespace() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *CreateNamespaceResponse) GetNamespaceOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Namespace, true
}

// SetNamespace sets field value
func (o *CreateNamespaceResponse) SetNamespace(v []string) {
	o.Namespace = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *CreateNamespaceResponse) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNamespaceResponse) GetPropertiesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return map[string]string{}, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *CreateNamespaceResponse) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *CreateNamespaceResponse) SetProperties(v map[string]string) {
	o.Properties = v
}

func (o CreateNamespaceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNamespaceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["namespace"] = o.Namespace
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

func (o *CreateNamespaceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNamespaceResponse := _CreateNamespaceResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNamespaceResponse)

	if err != nil {
		return err
	}

	*o = CreateNamespaceResponse(varCreateNamespaceResponse)

	return err
}

type NullableCreateNamespaceResponse struct {
	value *CreateNamespaceResponse
	isSet bool
}

func (v NullableCreateNamespaceResponse) Get() *CreateNamespaceResponse {
	return v.value
}

func (v *NullableCreateNamespaceResponse) Set(val *CreateNamespaceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNamespaceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNamespaceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNamespaceResponse(val *CreateNamespaceResponse) *NullableCreateNamespaceResponse {
	return &NullableCreateNamespaceResponse{value: val, isSet: true}
}

func (v NullableCreateNamespaceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNamespaceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


