/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetDefaultSpecUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetDefaultSpecUpdate{}

// SetDefaultSpecUpdate struct for SetDefaultSpecUpdate
type SetDefaultSpecUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	// Partition spec ID to set as the default, or -1 to set last added spec
	SpecId int32 `json:"spec-id"`
}

type _SetDefaultSpecUpdate SetDefaultSpecUpdate

// NewSetDefaultSpecUpdate instantiates a new SetDefaultSpecUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetDefaultSpecUpdate(specId int32) *SetDefaultSpecUpdate {
	this := SetDefaultSpecUpdate{}
	return &this
}

// NewSetDefaultSpecUpdateWithDefaults instantiates a new SetDefaultSpecUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetDefaultSpecUpdateWithDefaults() *SetDefaultSpecUpdate {
	this := SetDefaultSpecUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *SetDefaultSpecUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetDefaultSpecUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *SetDefaultSpecUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *SetDefaultSpecUpdate) SetAction(v string) {
	o.Action = &v
}

// GetSpecId returns the SpecId field value
func (o *SetDefaultSpecUpdate) GetSpecId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SpecId
}

// GetSpecIdOk returns a tuple with the SpecId field value
// and a boolean to check if the value has been set.
func (o *SetDefaultSpecUpdate) GetSpecIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpecId, true
}

// SetSpecId sets field value
func (o *SetDefaultSpecUpdate) SetSpecId(v int32) {
	o.SpecId = v
}

func (o SetDefaultSpecUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetDefaultSpecUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["spec-id"] = o.SpecId
	return toSerialize, nil
}

func (o *SetDefaultSpecUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spec-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetDefaultSpecUpdate := _SetDefaultSpecUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetDefaultSpecUpdate)

	if err != nil {
		return err
	}

	*o = SetDefaultSpecUpdate(varSetDefaultSpecUpdate)

	return err
}

type NullableSetDefaultSpecUpdate struct {
	value *SetDefaultSpecUpdate
	isSet bool
}

func (v NullableSetDefaultSpecUpdate) Get() *SetDefaultSpecUpdate {
	return v.value
}

func (v *NullableSetDefaultSpecUpdate) Set(val *SetDefaultSpecUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSetDefaultSpecUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSetDefaultSpecUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetDefaultSpecUpdate(val *SetDefaultSpecUpdate) *NullableSetDefaultSpecUpdate {
	return &NullableSetDefaultSpecUpdate{value: val, isSet: true}
}

func (v NullableSetDefaultSpecUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetDefaultSpecUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


