/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnaryExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnaryExpression{}

// UnaryExpression struct for UnaryExpression
type UnaryExpression struct {
	Type string `json:"type"`
	Term Term `json:"term"`
	Value map[string]interface{} `json:"value"`
}

type _UnaryExpression UnaryExpression

// NewUnaryExpression instantiates a new UnaryExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnaryExpression(type_ string, term Term, value map[string]interface{}) *UnaryExpression {
	this := UnaryExpression{}
	this.Type = type_
	this.Term = term
	this.Value = value
	return &this
}

// NewUnaryExpressionWithDefaults instantiates a new UnaryExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnaryExpressionWithDefaults() *UnaryExpression {
	this := UnaryExpression{}
	return &this
}

// GetType returns the Type field value
func (o *UnaryExpression) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UnaryExpression) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UnaryExpression) SetType(v string) {
	o.Type = v
}

// GetTerm returns the Term field value
func (o *UnaryExpression) GetTerm() Term {
	if o == nil {
		var ret Term
		return ret
	}

	return o.Term
}

// GetTermOk returns a tuple with the Term field value
// and a boolean to check if the value has been set.
func (o *UnaryExpression) GetTermOk() (*Term, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Term, true
}

// SetTerm sets field value
func (o *UnaryExpression) SetTerm(v Term) {
	o.Term = v
}

// GetValue returns the Value field value
func (o *UnaryExpression) GetValue() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *UnaryExpression) GetValueOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *UnaryExpression) SetValue(v map[string]interface{}) {
	o.Value = v
}

func (o UnaryExpression) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnaryExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["term"] = o.Term
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *UnaryExpression) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"term",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnaryExpression := _UnaryExpression{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnaryExpression)

	if err != nil {
		return err
	}

	*o = UnaryExpression(varUnaryExpression)

	return err
}

type NullableUnaryExpression struct {
	value *UnaryExpression
	isSet bool
}

func (v NullableUnaryExpression) Get() *UnaryExpression {
	return v.value
}

func (v *NullableUnaryExpression) Set(val *UnaryExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableUnaryExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableUnaryExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnaryExpression(val *UnaryExpression) *NullableUnaryExpression {
	return &NullableUnaryExpression{value: val, isSet: true}
}

func (v NullableUnaryExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnaryExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


