/*
Apache Iceberg REST Catalog API

Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package icebergclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveSnapshotsUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveSnapshotsUpdate{}

// RemoveSnapshotsUpdate struct for RemoveSnapshotsUpdate
type RemoveSnapshotsUpdate struct {
	BaseUpdate
	Action *string `json:"action,omitempty"`
	SnapshotIds []int64 `json:"snapshot-ids"`
}

type _RemoveSnapshotsUpdate RemoveSnapshotsUpdate

// NewRemoveSnapshotsUpdate instantiates a new RemoveSnapshotsUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveSnapshotsUpdate(snapshotIds []int64) *RemoveSnapshotsUpdate {
	this := RemoveSnapshotsUpdate{}
	return &this
}

// NewRemoveSnapshotsUpdateWithDefaults instantiates a new RemoveSnapshotsUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveSnapshotsUpdateWithDefaults() *RemoveSnapshotsUpdate {
	this := RemoveSnapshotsUpdate{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *RemoveSnapshotsUpdate) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemoveSnapshotsUpdate) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *RemoveSnapshotsUpdate) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *RemoveSnapshotsUpdate) SetAction(v string) {
	o.Action = &v
}

// GetSnapshotIds returns the SnapshotIds field value
func (o *RemoveSnapshotsUpdate) GetSnapshotIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}

	return o.SnapshotIds
}

// GetSnapshotIdsOk returns a tuple with the SnapshotIds field value
// and a boolean to check if the value has been set.
func (o *RemoveSnapshotsUpdate) GetSnapshotIdsOk() ([]int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnapshotIds, true
}

// SetSnapshotIds sets field value
func (o *RemoveSnapshotsUpdate) SetSnapshotIds(v []int64) {
	o.SnapshotIds = v
}

func (o RemoveSnapshotsUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveSnapshotsUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedBaseUpdate, errBaseUpdate := json.Marshal(o.BaseUpdate)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	errBaseUpdate = json.Unmarshal([]byte(serializedBaseUpdate), &toSerialize)
	if errBaseUpdate != nil {
		return map[string]interface{}{}, errBaseUpdate
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	toSerialize["snapshot-ids"] = o.SnapshotIds
	return toSerialize, nil
}

func (o *RemoveSnapshotsUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"snapshot-ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveSnapshotsUpdate := _RemoveSnapshotsUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveSnapshotsUpdate)

	if err != nil {
		return err
	}

	*o = RemoveSnapshotsUpdate(varRemoveSnapshotsUpdate)

	return err
}

type NullableRemoveSnapshotsUpdate struct {
	value *RemoveSnapshotsUpdate
	isSet bool
}

func (v NullableRemoveSnapshotsUpdate) Get() *RemoveSnapshotsUpdate {
	return v.value
}

func (v *NullableRemoveSnapshotsUpdate) Set(val *RemoveSnapshotsUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveSnapshotsUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveSnapshotsUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveSnapshotsUpdate(val *RemoveSnapshotsUpdate) *NullableRemoveSnapshotsUpdate {
	return &NullableRemoveSnapshotsUpdate{value: val, isSet: true}
}

func (v NullableRemoveSnapshotsUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveSnapshotsUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


