/*
Apache Iceberg REST Catalog API

Testing ConfigurationAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package icebergclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/danylokravchenko/iceberg-grpc/icebergclient"
)

func Test_icebergclient_ConfigurationAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ConfigurationAPIAPIService GetConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ConfigurationAPIAPI.GetConfig(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
